package com.stellarbeats.lyrics

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// ──────────────────────────────────────────────
// Core lyrics model
// ──────────────────────────────────────────────

/**
 * A single line of lyrics with an optional sync timestamp.
 *
 * If [timeMs] is null, the line is unsynced and should be displayed
 * as static text. If present, the player uses it to highlight the
 * current line and auto-scroll.
 *
 * @param timeMs Start time of this line in milliseconds from track start.
 *               null for unsynced lyrics or instrumental breaks.
 * @param text The lyric text. Empty string for instrumental markers.
 * @param isInstrumental If true, this represents a musical break with
 *                       no vocals. Display as "♪ Instrumental ♪" or similar.
 */
data class LyricsLine(
    val timeMs: Long?,
    val text: String,
    val isInstrumental: Boolean = false,
)

/**
 * Complete lyrics container with metadata and sync state.
 *
 * @param lines All lyric lines, sorted by [LyricsLine.timeMs] (nulls last).
 * @param isSynced Whether at least one line has a valid timestamp.
 * @param source Which provider returned these lyrics.
 * @param remoteUrl If available, a URL to view/edit lyrics on the source site.
 *                  Used for "View on LRCLIB" type actions.
 * @param providerColor Optional accent color for source attribution in UI.
 */
data class Lyrics(
    val lines: List<LyricsLine>,
    val isSynced: Boolean,
    val source: LyricsSource,
    val remoteUrl: String? = null,
    val providerColor: Long? = null,
) {
    /** The current line index for a given playback position. */
    fun indexOfTime(positionMs: Long): Int {
        if (!isSynced) return -1
        var best = -1
        for (i in lines.indices) {
            val t = lines[i].timeMs ?: continue
            if (t <= positionMs) best = i else break
        }
        return best
    }

    companion object {
        val EMPTY = Lyrics(
            lines = emptyList(),
            isSynced = false,
            source = LyricsSource.NONE,
        )
    }
}

// ──────────────────────────────────────────────
// Source enum
// ──────────────────────────────────────────────

enum class LyricsSource(
    val displayName: String,
    val priority: Int, // lower = tried first
    val accentColor: Long? = null,
) {
    /** LRCLIB.net — community-contributed LRC sync lyrics. Best quality. */
    LRCLIB("LRCLIB", priority = 0, accentColor = 0xFF6C63FF),

    /** YouTube timed captions (auto-generated or manual). */
    YOUTUBE("YouTube", priority = 1, accentColor = 0xFFFF0000),

    /** JioSaavn — plain text, no sync. */
    JIOSAAVN("JioSaavn", priority = 2, accentColor = 0xFF00C853),

    /** No lyrics found. */
    NONE("None", priority = 99),
}

// ──────────────────────────────────────────────
// LRCLIB API models
// ──────────────────────────────────────────────

/**
 * LRCLIB search result.
 *
 * API: GET https://lrclib.net/api/search?q={query}
 * Returns array of these objects. We pick the best match.
 *
 * LRCLIB is fully free, no auth, rate-limited to ~20 req/min.
 * It has the largest database of synced LRC lyrics outside of
 * Musixmatch's paid API.
 */
@Serializable
data class LrcLibResult(
    @SerialName("id") val id: Int,
    @SerialName("trackName") val trackName: String,
    @SerialName("artistName") val artistName: String,
    @SerialName("albumName") val albumName: String? = null,
    @SerialName("duration") val duration: Float? = null,
    @SerialName("instrumental") val instrumental: Boolean = false,
    @SerialName("plainLyrics") val plainLyrics: String? = null,
    @SerialName("syncedLyrics") val syncedLyrics: String? = null,
)

/**
 * LRCLIB single-track fetch response.
 *
 * API: GET https://lrclib.net/api/get?artist_name=X&track_name=X
 * Same shape as search result but single object (or 404).
 */
typealias LrcLibTrack = LrcLibResult

// ──────────────────────────────────────────────
// YouTube captions model
// ──────────────────────────────────────────────

/**
 * Parsed YouTube caption track.
 *
 * YouTube provides captions via a `timedtext` URL that returns XML.
 * We parse the XML into this flat list of timed lines.
 *
 * YouTube captions come in two flavors:
 * - **Manual**: High quality, properly line-broken
 * - **Auto-generated**: Often single-word timestamps, need merging
 *
 * The [isAutoGenerated] flag lets the UI decide whether to show
 * word-by-word karaoke or merged lines.
 */
data class YouTubeCaptionTrack(
    val lines: List<LyricsLine>,
    val isAutoGenerated: Boolean,
)

// ──────────────────────────────────────────────
// LRC format parser result
// ──────────────────────────────────────────────

/**
 * Raw LRC parse result before normalization.
 *
 * LRC format:
 * ```
 * [ti:Song Title]
 * [ar:Artist Name]
 * [al:Album Name]
 * [00:12.34]First line of lyrics
 * [00:15.67]Second line
 * [00:20.00]<instrumental>
 * ```
 *
 * Metadata tags ([ti:], [ar:], etc.) are extracted but not used
 * for display — we already have that from the player response.
 */
data class LrcParseResult(
    val lines: List<LyricsLine>,
    val metadata: LrcMetadata,
    val parseErrors: Int = 0,
)

@Serializable
data class LrcMetadata(
    val title: String? = null,
    val artist: String? = null,
    val album: String? = null,
    val by: String? = null,       // LRC creator
    val offset: Long = 0,         // Global offset in milliseconds
)

// ──────────────────────────────────────────────
// Exceptions
// ──────────────────────────────────────────────

open class LyricsException(message: String, cause: Throwable? = null) : Exception(message, cause)

class LrcParseException(message: String, cause: Throwable? = null) : LyricsException(message, cause)

class CaptionParseException(message: String, cause: Throwable? = null) : LyricsException(message, cause)
